
[Settings]

ID = "0592c43a-58e4-4f36-9b15-ca82585e522b"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]

  publish = "dist/"